var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. Interface', 'Page2.html',{'tt':'1. Interface','sb':'Page2.html'},
			['1.1 flujo de decisiones consol... ', 'LinkedDocuments/flujo%20de%20decisiones%20consola%202024.dia',{'tt':'1.1 flujo de decisiones consola 2024.dia','sb':'LinkedDocuments/flujo%20de%20decisiones%20consola%202024.dia'},],
],
		['2. Procesar inventario  de Pla... ', 'Page4.html',{'tt':'2. Procesar inventario  de Plantaciones','sb':'Page4.html'},
			['2.1 Formato de datos', 'Page5.html',{'tt':'2.1 Formato de datos','sb':'Page5.html'},],
			['2.2 Procesamiento', 'Page6.html',{'tt':'2.2 Procesamiento','sb':'Page6.html'},],
			['2.3 Definición de productos de... ', 'Page7.html',{'tt':'2.3 Definición de productos de trozado','sb':'Page7.html'},],
			['2.4 Ejemplo de datos', '../../../../Documents/uniMatlab_INNOVAR%20-%20trozarArbol/datos/datosPlantaciones/datosInventarioPlantaciones.xls',{'tt':'2.4 Ejemplo de datos','sb':'../../../../Documents/uniMatlab_INNOVAR%20-%20trozarArbol/datos/datosPlantaciones/datosInventarioPlantaciones.xls'},],
			['2.5 Diagrama de Flujo del cálc... ', 'Page9.html',{'tt':'2.5 Diagrama de Flujo del cálculo','sb':'Page9.html'},],
			['2.6 Resultados', 'Page10.html',{'tt':'2.6 Resultados','sb':'Page10.html'},],
],
		['3. Procesar inventario  de Bos... ', 'Page11.html',{'tt':'3. Procesar inventario  de Bosque Nativo','sb':'Page11.html'},
			['3.1 Formato de datos', 'Page12.html',{'tt':'3.1 Formato de datos','sb':'Page12.html'},],
			['3.2 Procesamiento', 'Page13.html',{'tt':'3.2 Procesamiento','sb':'Page13.html'},],
			['3.3 Ejemplo de datos', '../../../../Documents/uniMatlab_INNOVAR%20-%20trozarArbol/datos/datosBosqueNativo/datosInventarioBosqueNativo.xls',{'tt':'3.3 Ejemplo de datos','sb':'../../../../Documents/uniMatlab_INNOVAR%20-%20trozarArbol/datos/datosBosqueNativo/datosInventarioBosqueNativo.xls'},],
			['3.4 Resultados', 'Page15.html',{'tt':'3.4 Resultados','sb':'Page15.html'},],
],
		['4. Instalador', 'Page16.html',{'tt':'4. Instalador','sb':'Page16.html'},
			['4.1 calcuLEMUs_Installer_mcr(6... ', 'Page17.html',{'tt':'4.1 calcuLEMUs_Installer_mcr(64bit).exe','sb':'Page17.html'},],
],
		['5. Créditos', 'Page18.html',{'tt':'5. Créditos','sb':'Page18.html'},],
		['6. Simulador Piltriquitrón', 'Page19.html',{'tt':'6. Simulador Piltriquitrón','sb':'Page19.html'},
			['6.1 Capítulo 5. Modelización d... ', 'https://www.omniascience.com/books/index.php/monographs/catalog/view/71/275/393-1',{'tt':'6.1 Capítulo 5. Modelización del crecimiento y la producción de los rodales a través de Índices de Densidad','sb':'https://www.omniascience.com/books/index.php/monographs/catalog/view/71/275/393-1'},],
			['6.2 Proyectar un Inventario de... ', 'Page21.html',{'tt':'6.2 Proyectar un Inventario de Diámetros','sb':'Page21.html'},],
			['6.3 Generar Tabla de Producció... ', 'Page22.html',{'tt':'6.3 Generar Tabla de Producción','sb':'Page22.html'},],
],

]
];